### ISSUE TITLE
Example code not working on latest macOS

### ISSUE THREAD

**Issue by ShivamJoker** [coreybutler/node-mac#31]
The terminal says 
```
Installation Complete
---------------------
Hello World started!
Visit http://127.0.0.1:3000 to see it in action.
```
But I couldn't find anything in the activity monitor also, I am just running the example code and there is no log in the `~/Library/Logs`
and plist in `~/Library/LaunchAgents`

When I run hello world with node the server works.

here is the screenshot 
![image](https://user-images.githubusercontent.com/23727670/83651085-b8309f00-a5d6-11ea-8435-64feeaa1abe0.png)

**Comment by coreybutler** [comment]
Fixed this in v1.0.0.

There were a number of things happening, including outdated plist data (which is used to populate the activity monitor). However; the activity monitor may or may not display the name of the process (it may just display `node`) depending on the version of Node you're running. There is an upstream issue at https://github.com/nodejs/node/issues/28945 causing this in various versions.

Using Node 13.5.0, the results look like this:

<img width="1044" alt="catalina" src="https://user-images.githubusercontent.com/770982/86995948-f0944180-c16f-11ea-81c9-0561435092aa.png">

<img width="912" alt="logs" src="https://user-images.githubusercontent.com/770982/86995965-fa1da980-c16f-11ea-89d6-9204fb172df6.png">

Running Node 14.0.0+ (affected by the upstream error):

![image](https://user-images.githubusercontent.com/770982/86996056-410b9f00-c170-11ea-88cd-632f8420a2b4.png)

This library can't do anything about the naming issues since it's a problem in Node core. However; the daemons will still run and output logs normally.

**Comment by ShivamJoker** [comment]
It is still crashing while running hello world this is in the log
```js
# Hello World Errorsinternal/fs/utils.js:230
    throw err;
    ^

Error: EPERM: operation not permitted, open '/Users/shivam/Documents/web/gitclones/node-mac/lib/wrapper.js'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:22)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -1,
  syscall: 'open',
  code: 'EPERM',
  path: '/Users/shivam/Documents/web/gitclones/node-mac/lib/wrapper.js'
}
```

**Comment by dhananjaysharma-me** [comment]
# Authentication Errorsnode:internal/fs/utils:344
    throw err;
    ^

Error: EPERM: operation not permitted, open '/Users/dhananjay/Desktop/Projects/user-authentication-module/backend-app/node_modules/node-mac/lib/wrapper.js'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1114:18)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -1,
  syscall: 'open',
  code: 'EPERM',
  path: '/Users/dhananjay/Desktop/Projects/user-authentication-module/backend-app/node_modules/node-mac/lib/wrapper.js'
}

Node.js v17.3.1

Facing Above issue
@ShivamJoker Have you found any solution?

**Comment by sangyookm** [comment]
having same problem too

**Comment by galaxy-s10** [comment]
same

**Comment by coreybutler** [comment]
For those experiencing permission issues (`EPERM`), your _app_ has to have permissions to _run_. Granting permission to the library won't do anything because the library is only used to install/uninstall the daemon. If you run everything as sudo/root, it should work. If you cannot do that, you have to ensure the user account you are running the app with has permissions to the appropriate directories, files, etc.

If you're successfully installing your app but not seeing it in the activity monitor, that could be due to how macOS handles process titles. When this issue was opened, you could not reliable set the title of a process on macOS (I wrote the Node docs on that, so it stands out to me). The docs have changed since then, but I have not kept up with the nuances of how macOS handles process titles. Bottom line: you may not see the process show up in the activity monitor. Relevant docs are available [here](https://nodejs.org/api/child_process.html#:~:text=Certain%20platforms%20(macOS%2C%20Linux)%20will%20use%20the%20value%20of%20argv%5B0%5D%20for%20the%20process%20title%20while%20others%20(Windows%2C%20SunOS)%20will%20use%20command).

This issue was opened a long time ago and the "latest" version of macOS is very different now. I only have an old iMac which cannot run newer versions of macOS.

I'm closing this, mostly due to age and the fact most of these issues are related to user permissions, not the library.
